### ISSUE TITLE
Assigning Key Code's to buttons

### ISSUE THREAD

**Issue by GabrieleNunez** [mixer/interactive-node#49]
I'm seeing that there is a key code option I can assign to a button control, however any attempt to do so is doesn't seem to register.  I've tried going through control.update, the protected control.updateAttribute, and then by doing client.updateControls 

I can confirm my other calls via updateControls do work when setting text and spark cost. Protocol defines it as a JavaScript key code if I remember right so any clues as to what I am doing wrong ?

**Comment by ProbablePrime** [comment]
Are you looking to assign a keycode to a button that can be used on the participant side within the browser?

This is a feature that didn't quite make its way into Interactive 2 but we're working on it making a return.

**Comment by GabrieleNunez** [comment]
Ahhh ok then yes that is exactly what I mean.  Thank you for the help :)

**Comment by EthanWaite** [comment]
(Closing out some old GitHub issues. 😊)

Keyboard controls were re-implemented in Interactive 2; see `examples/keyboardControls.ts` for a full demo
